project:
  type: website
  output-dir: docs

website:
  title: "Michael Gelfand"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



